apiVersion: v1
kind: Service
metadata:
  name: substrate-server
  namespace: substrate
  labels:
    app.kubernetes.io/name: substrate-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: substrate-server
  ports:
    - name: http
      port: 8080
      targetPort: http
