// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type Approval string

const (
	ApprovalProposed Approval = "proposed"
	ApprovalApproved Approval = "approved"
	ApprovalRejected Approval = "rejected"
)

func (e *Approval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Approval(s)
	case string:
		*e = Approval(s)
	default:
		return fmt.Errorf("unsupported scan type for Approval: %T", src)
	}
	return nil
}

type NullApproval struct {
	Approval Approval
	Valid    bool // Valid is true if Approval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullApproval) Scan(value interface{}) error {
	if value == nil {
		ns.Approval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Approval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullApproval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Approval), nil
}

type EdgeRelation string

const (
	EdgeRelationSupersedes  EdgeRelation = "supersedes"
	EdgeRelationContradicts EdgeRelation = "contradicts"
	EdgeRelationCausedBy    EdgeRelation = "caused_by"
	EdgeRelationRelatesTo   EdgeRelation = "relates_to"
	EdgeRelationUsesSkill   EdgeRelation = "uses_skill"
	EdgeRelationDerivedFrom EdgeRelation = "derived_from"
)

func (e *EdgeRelation) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EdgeRelation(s)
	case string:
		*e = EdgeRelation(s)
	default:
		return fmt.Errorf("unsupported scan type for EdgeRelation: %T", src)
	}
	return nil
}

type NullEdgeRelation struct {
	EdgeRelation EdgeRelation
	Valid        bool // Valid is true if EdgeRelation is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEdgeRelation) Scan(value interface{}) error {
	if value == nil {
		ns.EdgeRelation, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EdgeRelation.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEdgeRelation) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EdgeRelation), nil
}

type InstructionKind string

const (
	InstructionKindRule       InstructionKind = "rule"
	InstructionKindConstraint InstructionKind = "constraint"
	InstructionKindConvention InstructionKind = "convention"
)

func (e *InstructionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstructionKind(s)
	case string:
		*e = InstructionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for InstructionKind: %T", src)
	}
	return nil
}

type NullInstructionKind struct {
	InstructionKind InstructionKind
	Valid           bool // Valid is true if InstructionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstructionKind) Scan(value interface{}) error {
	if value == nil {
		ns.InstructionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstructionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstructionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstructionKind), nil
}

type InstructionStatus string

const (
	InstructionStatusActive   InstructionStatus = "active"
	InstructionStatusProposed InstructionStatus = "proposed"
	InstructionStatusRetired  InstructionStatus = "retired"
)

func (e *InstructionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstructionStatus(s)
	case string:
		*e = InstructionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InstructionStatus: %T", src)
	}
	return nil
}

type NullInstructionStatus struct {
	InstructionStatus InstructionStatus
	Valid             bool // Valid is true if InstructionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstructionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InstructionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstructionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstructionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstructionStatus), nil
}

type MemberRole string

const (
	MemberRoleMember MemberRole = "member"
	MemberRoleLead   MemberRole = "lead"
	MemberRoleAdmin  MemberRole = "admin"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type MemoryKind string

const (
	MemoryKindFact        MemoryKind = "fact"
	MemoryKindDecision    MemoryKind = "decision"
	MemoryKindIncident    MemoryKind = "incident"
	MemoryKindLesson      MemoryKind = "lesson"
	MemoryKindObservation MemoryKind = "observation"
)

func (e *MemoryKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemoryKind(s)
	case string:
		*e = MemoryKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MemoryKind: %T", src)
	}
	return nil
}

type NullMemoryKind struct {
	MemoryKind MemoryKind
	Valid      bool // Valid is true if MemoryKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemoryKind) Scan(value interface{}) error {
	if value == nil {
		ns.MemoryKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemoryKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemoryKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemoryKind), nil
}

type MemoryStatus string

const (
	MemoryStatusConfirmed  MemoryStatus = "confirmed"
	MemoryStatusProbable   MemoryStatus = "probable"
	MemoryStatusUnverified MemoryStatus = "unverified"
	MemoryStatusConflicted MemoryStatus = "conflicted"
	MemoryStatusDeprecated MemoryStatus = "deprecated"
	MemoryStatusSuperseded MemoryStatus = "superseded"
)

func (e *MemoryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemoryStatus(s)
	case string:
		*e = MemoryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MemoryStatus: %T", src)
	}
	return nil
}

type NullMemoryStatus struct {
	MemoryStatus MemoryStatus
	Valid        bool // Valid is true if MemoryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemoryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MemoryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemoryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemoryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemoryStatus), nil
}

type MemoryTier string

const (
	MemoryTierWorking  MemoryTier = "working"
	MemoryTierEpisodic MemoryTier = "episodic"
	MemoryTierSemantic MemoryTier = "semantic"
)

func (e *MemoryTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemoryTier(s)
	case string:
		*e = MemoryTier(s)
	default:
		return fmt.Errorf("unsupported scan type for MemoryTier: %T", src)
	}
	return nil
}

type NullMemoryTier struct {
	MemoryTier MemoryTier
	Valid      bool // Valid is true if MemoryTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemoryTier) Scan(value interface{}) error {
	if value == nil {
		ns.MemoryTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemoryTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemoryTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemoryTier), nil
}

type PrincipalKind string

const (
	PrincipalKindUser  PrincipalKind = "user"
	PrincipalKindAgent PrincipalKind = "agent"
)

func (e *PrincipalKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrincipalKind(s)
	case string:
		*e = PrincipalKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PrincipalKind: %T", src)
	}
	return nil
}

type NullPrincipalKind struct {
	PrincipalKind PrincipalKind
	Valid         bool // Valid is true if PrincipalKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrincipalKind) Scan(value interface{}) error {
	if value == nil {
		ns.PrincipalKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrincipalKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrincipalKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrincipalKind), nil
}

type ReviewKind string

const (
	ReviewKindPromotion         ReviewKind = "promotion"
	ReviewKindInstructionChange ReviewKind = "instruction_change"
	ReviewKindSkillProposal     ReviewKind = "skill_proposal"
	ReviewKindContradiction     ReviewKind = "contradiction"
	ReviewKindDriftProposal     ReviewKind = "drift_proposal"
	ReviewKindImportConflict    ReviewKind = "import_conflict"
)

func (e *ReviewKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewKind(s)
	case string:
		*e = ReviewKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewKind: %T", src)
	}
	return nil
}

type NullReviewKind struct {
	ReviewKind ReviewKind
	Valid      bool // Valid is true if ReviewKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewKind) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewKind), nil
}

type ReviewStatus string

const (
	ReviewStatusOpen      ReviewStatus = "open"
	ReviewStatusApproved  ReviewStatus = "approved"
	ReviewStatusRejected  ReviewStatus = "rejected"
	ReviewStatusWithdrawn ReviewStatus = "withdrawn"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus
	Valid        bool // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type ScopeKind string

const (
	ScopeKindGlobal  ScopeKind = "global"
	ScopeKindOrg     ScopeKind = "org"
	ScopeKindTeam    ScopeKind = "team"
	ScopeKindProject ScopeKind = "project"
	ScopeKindRepo    ScopeKind = "repo"
	ScopeKindBranch  ScopeKind = "branch"
	ScopeKindTask    ScopeKind = "task"
	ScopeKindSession ScopeKind = "session"
	ScopeKindUser    ScopeKind = "user"
)

func (e *ScopeKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScopeKind(s)
	case string:
		*e = ScopeKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ScopeKind: %T", src)
	}
	return nil
}

type NullScopeKind struct {
	ScopeKind ScopeKind
	Valid     bool // Valid is true if ScopeKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScopeKind) Scan(value interface{}) error {
	if value == nil {
		ns.ScopeKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScopeKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScopeKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScopeKind), nil
}

type TrustLevel string

const (
	TrustLevelHumanAdmin       TrustLevel = "human_admin"
	TrustLevelHuman            TrustLevel = "human"
	TrustLevelAgentInteractive TrustLevel = "agent_interactive"
	TrustLevelAgentAutonomous  TrustLevel = "agent_autonomous"
)

func (e *TrustLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TrustLevel(s)
	case string:
		*e = TrustLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for TrustLevel: %T", src)
	}
	return nil
}

type NullTrustLevel struct {
	TrustLevel TrustLevel
	Valid      bool // Valid is true if TrustLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTrustLevel) Scan(value interface{}) error {
	if value == nil {
		ns.TrustLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TrustLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTrustLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TrustLevel), nil
}

type VerificationType string

const (
	VerificationTypeCode           VerificationType = "code"
	VerificationTypeHuman          VerificationType = "human"
	VerificationTypeAgentInference VerificationType = "agent_inference"
)

func (e *VerificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationType(s)
	case string:
		*e = VerificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationType: %T", src)
	}
	return nil
}

type NullVerificationType struct {
	VerificationType VerificationType
	Valid            bool // Valid is true if VerificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationType) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationType), nil
}

type Visibility string

const (
	VisibilityOwner  Visibility = "owner"
	VisibilityTeam   Visibility = "team"
	VisibilityOrg    Visibility = "org"
	VisibilityGlobal Visibility = "global"
)

func (e *Visibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Visibility(s)
	case string:
		*e = Visibility(s)
	default:
		return fmt.Errorf("unsupported scan type for Visibility: %T", src)
	}
	return nil
}

type NullVisibility struct {
	Visibility Visibility
	Valid      bool // Valid is true if Visibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.Visibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Visibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Visibility), nil
}

type ApiToken struct {
	ID          pgtype.UUID
	PrincipalID pgtype.UUID
	Machine     string
	TokenHash   []byte
	Scopes      []string
	ExpiresAt   pgtype.Timestamptz
	RevokedAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type Audit struct {
	ID          int64
	At          pgtype.Timestamptz
	ActorID     pgtype.UUID
	Action      string
	SubjectType string
	SubjectID   pgtype.UUID
	ScopeID     pgtype.UUID
	Before      []byte
	After       []byte
	Reason      *string
	RequestID   *string
}

type IngestReceipt struct {
	ClientID    pgtype.UUID
	PrincipalID pgtype.UUID
	SubjectType string
	SubjectID   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type Instruction struct {
	ID           pgtype.UUID
	ScopeID      pgtype.UUID
	Visibility   Visibility
	OwnerID      pgtype.UUID
	Kind         InstructionKind
	Key          string
	Body         string
	Status       InstructionStatus
	SupersededBy pgtype.UUID
	CreatedBy    pgtype.UUID
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type Membership struct {
	PrincipalID pgtype.UUID
	TeamID      pgtype.UUID
	Role        MemberRole
}

type Memory struct {
	ID               pgtype.UUID
	ScopeID          pgtype.UUID
	Visibility       Visibility
	OwnerID          pgtype.UUID
	Tier             MemoryTier
	Kind             MemoryKind
	Title            string
	Body             string
	Identifiers      []string
	Embedding        *pgvector.Vector
	Fts              interface{}
	Status           MemoryStatus
	SupersededBy     pgtype.UUID
	Source           []byte
	Verification     []byte
	VerificationType *VerificationType
	ValidFromCommit  *string
	LastVerifiedAt   pgtype.Timestamptz
	StaleReason      *string
	RetrievedCount   int32
	UsefulCount      int32
	IncorrectCount   int32
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type MemoryEdge struct {
	FromID    pgtype.UUID
	ToID      pgtype.UUID
	Relation  EdgeRelation
	CreatedBy pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

type MemoryFeedback struct {
	ID          pgtype.UUID
	MemoryID    pgtype.UUID
	PrincipalID pgtype.UUID
	Trust       TrustLevel
	Useful      *bool
	Incorrect   *bool
	Reason      *string
	SessionID   *string
	CreatedAt   pgtype.Timestamptz
}

type Org struct {
	ID   pgtype.UUID
	Name string
}

type Preference struct {
	ID         pgtype.UUID
	ScopeID    pgtype.UUID
	Visibility Visibility
	OwnerID    pgtype.UUID
	Key        string
	Body       string
	Status     InstructionStatus
	CreatedBy  pgtype.UUID
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Principal struct {
	ID          pgtype.UUID
	Kind        PrincipalKind
	DisplayName string
	Trust       TrustLevel
	MintedBy    pgtype.UUID
	DisabledAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

type ProjectGrant struct {
	ProjectScopeID pgtype.UUID
	TeamID         pgtype.UUID
	Role           MemberRole
}

type RepoRemote struct {
	RemoteNorm  string
	RepoScopeID pgtype.UUID
	CreatedBy   pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

type ReviewItem struct {
	ID         pgtype.UUID
	Kind       ReviewKind
	ScopeID    pgtype.UUID
	TeamID     pgtype.UUID
	Payload    []byte
	ProposedBy pgtype.UUID
	Status     ReviewStatus
	DecidedBy  pgtype.UUID
	DecidedAt  pgtype.Timestamptz
	Reason     *string
	CreatedAt  pgtype.Timestamptz
}

type Scope struct {
	ID       pgtype.UUID
	Kind     ScopeKind
	ParentID pgtype.UUID
	Key      string
	TeamID   pgtype.UUID
	Depth    int16
	Path     string
}

type Skill struct {
	ID              pgtype.UUID
	Name            string
	ScopeID         pgtype.UUID
	Visibility      Visibility
	OwnerID         pgtype.UUID
	Description     string
	Tags            []string
	Embedding       *pgvector.Vector
	ActiveVersionID pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type SkillVersion struct {
	ID         pgtype.UUID
	SkillID    pgtype.UUID
	Semver     string
	GitSha     string
	GitPath    string
	AuthorID   pgtype.UUID
	Reason     *string
	SourceTask *string
	Approval   Approval
	CreatedAt  pgtype.Timestamptz
}

type Team struct {
	ID    pgtype.UUID
	OrgID pgtype.UUID
	Name  string
}

type Workspace struct {
	ID            pgtype.UUID
	RepoScopeID   pgtype.UUID
	BranchScopeID pgtype.UUID
	PrincipalID   pgtype.UUID
	Machine       string
	WorktreePath  string
	GitSha        *string
	Dirty         bool
	LastSeenAt    pgtype.Timestamptz
}
