// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decideReviewItem = `-- name: DecideReviewItem :one
UPDATE review_item
SET status = $2, decided_by = $3, decided_at = now(), reason = $4
WHERE id = $1 AND status = 'open'
RETURNING id, status, decided_by, decided_at, reason
`

type DecideReviewItemParams struct {
	ID        pgtype.UUID
	Status    ReviewStatus
	DecidedBy pgtype.UUID
	Reason    *string
}

type DecideReviewItemRow struct {
	ID        pgtype.UUID
	Status    ReviewStatus
	DecidedBy pgtype.UUID
	DecidedAt pgtype.Timestamptz
	Reason    *string
}

func (q *Queries) DecideReviewItem(ctx context.Context, arg DecideReviewItemParams) (DecideReviewItemRow, error) {
	row := q.db.QueryRow(ctx, decideReviewItem,
		arg.ID,
		arg.Status,
		arg.DecidedBy,
		arg.Reason,
	)
	var i DecideReviewItemRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.DecidedBy,
		&i.DecidedAt,
		&i.Reason,
	)
	return i, err
}

const getIngestReceipt = `-- name: GetIngestReceipt :one
SELECT client_id, principal_id, subject_type, subject_id
FROM ingest_receipt
WHERE client_id = $1
`

type GetIngestReceiptRow struct {
	ClientID    pgtype.UUID
	PrincipalID pgtype.UUID
	SubjectType string
	SubjectID   pgtype.UUID
}

func (q *Queries) GetIngestReceipt(ctx context.Context, clientID pgtype.UUID) (GetIngestReceiptRow, error) {
	row := q.db.QueryRow(ctx, getIngestReceipt, clientID)
	var i GetIngestReceiptRow
	err := row.Scan(
		&i.ClientID,
		&i.PrincipalID,
		&i.SubjectType,
		&i.SubjectID,
	)
	return i, err
}

const getMemory = `-- name: GetMemory :one
SELECT id, scope_id, visibility, owner_id, tier, kind, title, body, identifiers,
  status, superseded_by, source, verification, created_by
FROM memory
WHERE id = $1
`

type GetMemoryRow struct {
	ID           pgtype.UUID
	ScopeID      pgtype.UUID
	Visibility   Visibility
	OwnerID      pgtype.UUID
	Tier         MemoryTier
	Kind         MemoryKind
	Title        string
	Body         string
	Identifiers  []string
	Status       MemoryStatus
	SupersededBy pgtype.UUID
	Source       []byte
	Verification []byte
	CreatedBy    pgtype.UUID
}

func (q *Queries) GetMemory(ctx context.Context, id pgtype.UUID) (GetMemoryRow, error) {
	row := q.db.QueryRow(ctx, getMemory, id)
	var i GetMemoryRow
	err := row.Scan(
		&i.ID,
		&i.ScopeID,
		&i.Visibility,
		&i.OwnerID,
		&i.Tier,
		&i.Kind,
		&i.Title,
		&i.Body,
		&i.Identifiers,
		&i.Status,
		&i.SupersededBy,
		&i.Source,
		&i.Verification,
		&i.CreatedBy,
	)
	return i, err
}

const getScope = `-- name: GetScope :one
SELECT id, kind, parent_id, key, team_id, depth, path::text AS path
FROM scope
WHERE id = $1
`

type GetScopeRow struct {
	ID       pgtype.UUID
	Kind     ScopeKind
	ParentID pgtype.UUID
	Key      string
	TeamID   pgtype.UUID
	Depth    int16
	Path     string
}

func (q *Queries) GetScope(ctx context.Context, id pgtype.UUID) (GetScopeRow, error) {
	row := q.db.QueryRow(ctx, getScope, id)
	var i GetScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ParentID,
		&i.Key,
		&i.TeamID,
		&i.Depth,
		&i.Path,
	)
	return i, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit (actor_id, action, subject_type, subject_id, scope_id, reason, request_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertAuditParams struct {
	ActorID     pgtype.UUID
	Action      string
	SubjectType string
	SubjectID   pgtype.UUID
	ScopeID     pgtype.UUID
	Reason      *string
	RequestID   *string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.Action,
		arg.SubjectType,
		arg.SubjectID,
		arg.ScopeID,
		arg.Reason,
		arg.RequestID,
	)
	return err
}

const insertIngestReceipt = `-- name: InsertIngestReceipt :exec
INSERT INTO ingest_receipt (client_id, principal_id, subject_type, subject_id)
VALUES ($1, $2, $3, $4)
`

type InsertIngestReceiptParams struct {
	ClientID    pgtype.UUID
	PrincipalID pgtype.UUID
	SubjectType string
	SubjectID   pgtype.UUID
}

func (q *Queries) InsertIngestReceipt(ctx context.Context, arg InsertIngestReceiptParams) error {
	_, err := q.db.Exec(ctx, insertIngestReceipt,
		arg.ClientID,
		arg.PrincipalID,
		arg.SubjectType,
		arg.SubjectID,
	)
	return err
}

const insertMemory = `-- name: InsertMemory :one
INSERT INTO memory (
  id, scope_id, visibility, owner_id, tier, kind, title, body, identifiers,
  status, source, verification, created_by
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, status
`

type InsertMemoryParams struct {
	ID           pgtype.UUID
	ScopeID      pgtype.UUID
	Visibility   Visibility
	OwnerID      pgtype.UUID
	Tier         MemoryTier
	Kind         MemoryKind
	Title        string
	Body         string
	Identifiers  []string
	Status       MemoryStatus
	Source       []byte
	Verification []byte
	CreatedBy    pgtype.UUID
}

type InsertMemoryRow struct {
	ID     pgtype.UUID
	Status MemoryStatus
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) (InsertMemoryRow, error) {
	row := q.db.QueryRow(ctx, insertMemory,
		arg.ID,
		arg.ScopeID,
		arg.Visibility,
		arg.OwnerID,
		arg.Tier,
		arg.Kind,
		arg.Title,
		arg.Body,
		arg.Identifiers,
		arg.Status,
		arg.Source,
		arg.Verification,
		arg.CreatedBy,
	)
	var i InsertMemoryRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const insertMemoryEdge = `-- name: InsertMemoryEdge :exec
INSERT INTO memory_edge (from_id, to_id, relation, created_by)
VALUES ($1, $2, $3, $4)
`

type InsertMemoryEdgeParams struct {
	FromID    pgtype.UUID
	ToID      pgtype.UUID
	Relation  EdgeRelation
	CreatedBy pgtype.UUID
}

func (q *Queries) InsertMemoryEdge(ctx context.Context, arg InsertMemoryEdgeParams) error {
	_, err := q.db.Exec(ctx, insertMemoryEdge,
		arg.FromID,
		arg.ToID,
		arg.Relation,
		arg.CreatedBy,
	)
	return err
}

const insertReviewItem = `-- name: InsertReviewItem :one
INSERT INTO review_item (id, kind, scope_id, team_id, payload, proposed_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, kind, scope_id, team_id, payload, status, proposed_by, created_at
`

type InsertReviewItemParams struct {
	ID         pgtype.UUID
	Kind       ReviewKind
	ScopeID    pgtype.UUID
	TeamID     pgtype.UUID
	Payload    []byte
	ProposedBy pgtype.UUID
}

type InsertReviewItemRow struct {
	ID         pgtype.UUID
	Kind       ReviewKind
	ScopeID    pgtype.UUID
	TeamID     pgtype.UUID
	Payload    []byte
	Status     ReviewStatus
	ProposedBy pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) InsertReviewItem(ctx context.Context, arg InsertReviewItemParams) (InsertReviewItemRow, error) {
	row := q.db.QueryRow(ctx, insertReviewItem,
		arg.ID,
		arg.Kind,
		arg.ScopeID,
		arg.TeamID,
		arg.Payload,
		arg.ProposedBy,
	)
	var i InsertReviewItemRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ScopeID,
		&i.TeamID,
		&i.Payload,
		&i.Status,
		&i.ProposedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveInstructions = `-- name: ListActiveInstructions :many
SELECT id, scope_id, kind, key, body
FROM instruction
WHERE status = 'active'
  AND scope_id = ANY($1::uuid[])
`

type ListActiveInstructionsRow struct {
	ID      pgtype.UUID
	ScopeID pgtype.UUID
	Kind    InstructionKind
	Key     string
	Body    string
}

func (q *Queries) ListActiveInstructions(ctx context.Context, scopeIds []pgtype.UUID) ([]ListActiveInstructionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveInstructions, scopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveInstructionsRow
	for rows.Next() {
		var i ListActiveInstructionsRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Kind,
			&i.Key,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivePreferences = `-- name: ListActivePreferences :many
SELECT id, scope_id, key, body
FROM preference
WHERE status = 'active'
  AND scope_id = ANY($1::uuid[])
`

type ListActivePreferencesRow struct {
	ID      pgtype.UUID
	ScopeID pgtype.UUID
	Key     string
	Body    string
}

func (q *Queries) ListActivePreferences(ctx context.Context, scopeIds []pgtype.UUID) ([]ListActivePreferencesRow, error) {
	rows, err := q.db.Query(ctx, listActivePreferences, scopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActivePreferencesRow
	for rows.Next() {
		var i ListActivePreferencesRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Key,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApprovedSkills = `-- name: ListApprovedSkills :many
SELECT s.name, v.git_path, v.git_sha
FROM skill s
JOIN skill_version v ON v.id = s.active_version_id
WHERE s.active_version_id IS NOT NULL
  AND s.scope_id = ANY($1::uuid[])
ORDER BY s.name
`

type ListApprovedSkillsRow struct {
	Name    string
	GitPath string
	GitSha  string
}

func (q *Queries) ListApprovedSkills(ctx context.Context, scopeIds []pgtype.UUID) ([]ListApprovedSkillsRow, error) {
	rows, err := q.db.Query(ctx, listApprovedSkills, scopeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListApprovedSkillsRow
	for rows.Next() {
		var i ListApprovedSkillsRow
		if err := rows.Scan(&i.Name, &i.GitPath, &i.GitSha); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoryCache = `-- name: ListMemoryCache :many
SELECT id, scope_id, title, body, identifiers, status, updated_at
FROM memory
WHERE status IN ('confirmed', 'probable')
  AND updated_at > $1
ORDER BY updated_at ASC
`

type ListMemoryCacheRow struct {
	ID          pgtype.UUID
	ScopeID     pgtype.UUID
	Title       string
	Body        string
	Identifiers []string
	Status      MemoryStatus
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) ListMemoryCache(ctx context.Context, since pgtype.Timestamptz) ([]ListMemoryCacheRow, error) {
	rows, err := q.db.Query(ctx, listMemoryCache, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoryCacheRow
	for rows.Next() {
		var i ListMemoryCacheRow
		if err := rows.Scan(
			&i.ID,
			&i.ScopeID,
			&i.Title,
			&i.Body,
			&i.Identifiers,
			&i.Status,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewItems = `-- name: ListReviewItems :many
SELECT id, kind, scope_id, team_id, payload, status, proposed_by, decided_by, decided_at, reason, created_at
FROM review_item
WHERE ($1::uuid IS NULL OR team_id = $1)
  AND ($2::text IS NULL OR status = $2::review_status)
ORDER BY created_at DESC
`

type ListReviewItemsParams struct {
	TeamID pgtype.UUID
	Status *string
}

type ListReviewItemsRow struct {
	ID         pgtype.UUID
	Kind       ReviewKind
	ScopeID    pgtype.UUID
	TeamID     pgtype.UUID
	Payload    []byte
	Status     ReviewStatus
	ProposedBy pgtype.UUID
	DecidedBy  pgtype.UUID
	DecidedAt  pgtype.Timestamptz
	Reason     *string
	CreatedAt  pgtype.Timestamptz
}

func (q *Queries) ListReviewItems(ctx context.Context, arg ListReviewItemsParams) ([]ListReviewItemsRow, error) {
	rows, err := q.db.Query(ctx, listReviewItems, arg.TeamID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewItemsRow
	for rows.Next() {
		var i ListReviewItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ScopeID,
			&i.TeamID,
			&i.Payload,
			&i.Status,
			&i.ProposedBy,
			&i.DecidedBy,
			&i.DecidedAt,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupScope = `-- name: LookupScope :one
SELECT id, kind, parent_id, key, team_id, depth, path::text AS path
FROM scope
WHERE kind = $1
  AND key = $2
  AND parent_id IS NOT DISTINCT FROM $3
`

type LookupScopeParams struct {
	Kind     ScopeKind
	Key      string
	ParentID pgtype.UUID
}

type LookupScopeRow struct {
	ID       pgtype.UUID
	Kind     ScopeKind
	ParentID pgtype.UUID
	Key      string
	TeamID   pgtype.UUID
	Depth    int16
	Path     string
}

func (q *Queries) LookupScope(ctx context.Context, arg LookupScopeParams) (LookupScopeRow, error) {
	row := q.db.QueryRow(ctx, lookupScope, arg.Kind, arg.Key, arg.ParentID)
	var i LookupScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ParentID,
		&i.Key,
		&i.TeamID,
		&i.Depth,
		&i.Path,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const setMemorySupersededBy = `-- name: SetMemorySupersededBy :execrows
UPDATE memory
SET superseded_by = $2, status = 'superseded', updated_at = now()
WHERE id = $1 AND superseded_by IS NULL
`

type SetMemorySupersededByParams struct {
	ID           pgtype.UUID
	SupersededBy pgtype.UUID
}

func (q *Queries) SetMemorySupersededBy(ctx context.Context, arg SetMemorySupersededByParams) (int64, error) {
	result, err := q.db.Exec(ctx, setMemorySupersededBy, arg.ID, arg.SupersededBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
