// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getScope = `-- name: GetScope :one
SELECT id, kind, parent_id, key, team_id, depth, path::text AS path
FROM scope
WHERE id = $1
`

type GetScopeRow struct {
	ID       pgtype.UUID
	Kind     ScopeKind
	ParentID pgtype.UUID
	Key      string
	TeamID   pgtype.UUID
	Depth    int16
	Path     string
}

func (q *Queries) GetScope(ctx context.Context, id pgtype.UUID) (GetScopeRow, error) {
	row := q.db.QueryRow(ctx, getScope, id)
	var i GetScopeRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ParentID,
		&i.Key,
		&i.TeamID,
		&i.Depth,
		&i.Path,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1::int AS ok
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
